name: Build Docker and Push to ACR
description: Checks out a repo, builds a docker image from input params and pushes it to the Azure Container Registry.
inputs:
  branch:
    description: The branch of the repo that needs to be checked out.
    required: true
  acr_username:
    description: Token name for ACR
    required: true
  acr_password:
    description: Token value for ACR
    required: true
  registry:
    description: Name of registry on ACR (i.e. $registry.azurecr.io)
    required: true
  repo:
    description: Name of repository in ACR registry (i.e. $registry.azurecr.io/$repo)
    required: true
  dockerfile:
    description: Location of Dockerfile
    default: ./Dockerfile
  version_tag:
    description: Docker image version tag ((i.e. $registry.azurecr.io/$repo:$version_tag))
    default: latest
  pull_repo:
    description: Boolean flag to indicate whether or not to checkout repo
    default: true
runs:
  using: "composite"
  steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        if: ${{ input.pull_repo }}
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}.azurecr.io
          username: ${{ inputs.acr_username }}
          password: ${{ inputs.acr_password }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ inputs.registry }}.azurecr.io/${{ inputs.repo }}:${{ inputs.version_tag }}
          file: ${{ inputs.dockerfile }}
          cache-from: type=registry,ref=${{ inputs.registry }}.azurecr.io/${{ inputs.repo }}:buildcache
          cache-to: type=registry,ref=${{ inputs.registry }}.azurecr.io/${{ inputs.repo }}:buildcache,mode=max